language: java
services:
- docker
env:
  global:
  - GCP_PROJECT_ID=devops-eksamen-295808
  - IMAGE=gcr.io/devops-eksamen-295808/devops-eksamen
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: rQneCNNFT4+j9JwOBDOlif0NfVsb8C77dX5BoOUPElqEoP/c777i1dGFNSG4DwZPGiM/Rs1vneflLCOuWayVagk3t28MGmHwz7s92JDY1x4/LWyufxqnWbuIfabeb9oelmJn/A1axpXiDToC2hlDK2kfI3ASx0HUcZbXAGVRFv00fwXtGsgp432x0VxRewTh7CZh0emFkbpWSczqqnK+sEDm6r/efOlfH0De3qAIZbmfe8QuPBq+/RLjtRWgAkT0RDUI5poqenN8/TVF4m5BNhC0dEaDpz6n+FNnNmw+dr6rQbbY2182ne5Om2rWF1hlT7ribY1Emgt9rp/tBf+KmEU7rfg/XxMhDfYnvC+dQZ5Orh/wjdiV9VKCHbUptQAI20fjtThUJarp3719j3Vk68t0WUm5oT7BDITasfGU5sGtKUDEHlJlfjam8cCPyTAPslIDtW/Z9K9ytZ0hvLXWeeDppte6hMSOECd03zKanD9uZAWYM+NTEgslvxysVbBW4ZOjxWgK77EKKBBZi06FxS9+AJC6aF1tpLFO0/mGwqd77vMAwXtWzlDt80K/WdMqmV9wjfnN4mmPLF1OvxJ+7wFX+7QWusIJ/216lL3+E28ksZBPUVBI17t474/fTRatJuASZZ36DrTFCh5tx3l/bkETAicQZ0RpevXwyyzzTeU=
  - secure: OcLA0WEpDVE9nMNuelmWSCb/Vehk/0J8gmIBmtRKEbI6MZUI3kmgQWQXtfFfI6qN92+ea6kXUmsG2RwJbzhH0KzSvZ3jiKa1PLLFJpsSmBkTedBOWb0ppJigQ4Dq2ArUbaZEFMQRaD0Oe13CLA24IseDID5D3n3l+g6NPzuQQjGKFiXFFj8nak3QwHtgRTrE4IqXQ3YXO+Bh9o3oG97DBg+VqcXgN/3fS4stsnmfI8Fdfp8ItU1W06QTpkiI70ERushDS96kV8OklO06ayMaMAjgSNFubeH1SpUqBb2kHSMt1OiMxJGYpcyE/zbzwnRfxGpN3MGqDW9DaYY2jCfyUN069rQFbHNV9JA0M9HDur7NsYFyh80F7IIDiULqYIgKPuRkndMZbC9IWs+QQp4MJXTJu7530T0/MoqpT+Y5vsrFArwtANu9kO9qG5Q9t5VTlUMwmMdZFLurtnHoHJ28oC778k5DdvWpgPMTt85u7Bem0QVZajBCtLzYyi+nDb4VcCGxFl5CdvwZxX6z7Zo/htOD+7/mubxwu1pK5OlisNfzlt9x4W43dqzhFQE1U+OBT5yHfSqlW2UmF2JOqKBCFjNZSayx82rlQ7ozE+LOksLnJMUT1Spvb4geAX0THF/rjn332TxZQkTfBSD62ZXXCHthY5ojIoXmI+vcB5amWuE=
before_install:
- openssl aes-256-cbc -K $encrypted_add0310c1099_key -iv $encrypted_add0310c1099_iv
  -in terraform-292215-3bcfdd51423b.json.enc -out terraform-292215-3bcfdd51423b.json
  -d
- openssl aes-256-cbc -K $encrypted_08046dc9db46_key -iv $encrypted_08046dc9db46_iv
  -in GCP-key.json.enc -out GCP-key.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth configure-docker
- gcloud config set project "${GCP_PROJECT_ID}"
- gcloud components install beta
- gcloud auth activate-service-account --key-file=GCP-key.json
script:
- |-
  set -ex;
  docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
  docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
  set +x
