language: java
services:
- docker
env:
  global:
  - GCP_PROJECT_ID=terraform-292215
  - IMAGE=gcr.io/terraform-292215/devops-eksamen-10002
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_add0310c1099_key -iv $encrypted_add0310c1099_iv
  -in GCP-key.json.enc -out GCP-key.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth configure-docker
- gcloud config set project "${GCP_PROJECT_ID}"
- gcloud components install beta
- gcloud auth activate-service-account --key-file=GCP-key.json
script:
- |-
  set -ex;
  docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
  docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
  set +x
